[package]
name = "wallpaper-cava"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wallpaper-cava"
path = "src/main.rs"

[dependencies]
wallpaper-cava-config = { path = "../../crates/config" }
wallpaper-cava-audio = { path = "../../crates/audio" }
wallpaper-cava-render = { path = "../../crates/render" }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
gl = { workspace = true }
khronos-egl = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-egl = { workspace = true }
