[package]
name = "wallpaper-cava-infra"
version = "0.1.0"
edition = "2021"

[dependencies]
wallpaper-cava-domain = { path = "../domain" }
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
gl = { workspace = true }
khronos-egl = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-egl = { workspace = true }
